# Copyright 2020 Changkun Ou. All rights reserved.
# Use of this source code is governed by a MIT
# license that can be found in the LICENSE file.

version: "3"
services:
  redir:
    restart: always
    image: redir:latest
    environment:
      REDIR_CONF: ./data/redirconf.yml
    depends_on:
      - redis
    deploy:
      replicas: 3
    networks:
      - traefik_proxy
  redis:
    container_name: redis
    restart: always
    volumes:
      - ./data/redis:/data
    image: redis:6.0
    ports:
      - "6379:6379"
    networks:
      - traefik_proxy
networks:
  traefik_proxy:
    external: true